import { createFileRoute, Link } from "@tanstack/react-router";
import { Check, ChevronDown, Heart, Minus, Plus, Ruler, Star, Truck } from "lucide-react";
import { useMemo, useState } from "react";
import redDress from "@/assets/product-red-dress.jpg";
import campaignHero from "@/assets/campaign-hero.jpg";
import productGrid from "@/assets/products-grid.jpg";
import { Button, ProductCard, SectionTitle, useShop } from "@/components/ui";
import { featuredProduct, formatPrice, products } from "@/lib/catalog";

export const Route = createFileRoute("/product/$slug")({
  head: ({ params }) => ({ meta: [
    { title: `${products.find(p=>p.slug===params.slug)?.name ?? "Product"} — AARO` },
    { name: "description", content: "Explore the fit, colour, fabric and styling details of this AARO design." },
    { property: "og:title", content: `${products.find(p=>p.slug===params.slug)?.name ?? "Product"} — AARO` },
    { property: "og:description", content: "Modern design, considered fit, and complete product details." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: ProductPage,
});
const sizes=["XS","S","M","L","XL"];
function ProductPage(){ const {slug}=Route.useParams(); const product=products.find(p=>p.slug===slug)??featuredProduct; const [size,setSize]=useState(""); const [colour,setColour]=useState(product.colors[0]); const [pin,setPin]=useState(""); const [delivery,setDelivery]=useState<"idle"|"checking"|"yes"|"no">("idle"); const [guide,setGuide]=useState(false); const {addToBag,toggleWish,wishes}=useShop(); const gallery=useMemo(()=>[redDress,redDress,campaignHero,productGrid],[]); const checkPin=()=>{setDelivery("checking");setTimeout(()=>setDelivery(/^\d{6}$/.test(pin)?"yes":"no"),600)}; const add=()=>{if(!size){document.getElementById("sizes")?.scrollIntoView({behavior:"smooth",block:"center"});return}addToBag()}; return <main className="pb-20 md:pb-0">
  <div className="mx-auto max-w-[1440px] px-4 py-3 text-[10px] uppercase tracking-widest text-muted-foreground md:px-8">Home / {product.category} / {product.name}</div>
  <section className="mx-auto grid max-w-[1440px] gap-8 px-0 md:grid-cols-[minmax(0,1.35fr)_minmax(360px,.65fr)] md:px-8">
    <div className="grid snap-x snap-mandatory grid-flow-col auto-cols-[88%] gap-1 overflow-x-auto md:grid-flow-row md:grid-cols-2 md:overflow-visible">{gallery.map((image,index)=><div key={index} className="aspect-[3/4] snap-center overflow-hidden bg-muted"><img src={image} alt={`${product.name} view ${index+1}`} width={1024} height={1365} className="h-full w-full object-cover" loading={index===0?"eager":"lazy"} style={index===2?{objectPosition:"40% center"}:index===3?{objectPosition:"14% 15%"}:undefined}/></div>)}</div>
    <aside className="px-4 md:px-0"><div className="md:sticky md:top-28 md:pb-10"><div className="flex justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-muted-foreground">AARO</p><h1 className="mt-2 font-display text-3xl md:text-4xl">{product.name}</h1></div><Button variant="ghost" size="icon" onClick={()=>toggleWish(product.slug)} aria-label="Toggle wishlist"><Heart fill={wishes.has(product.slug)?"currentColor":"none"}/></Button></div><button className="mt-3 flex items-center gap-2 text-xs underline"><span className="flex text-accent"><Star size={13} fill="currentColor"/> 4.6</span><span>38 sample reviews</span></button><p className="mt-5 text-lg font-semibold">{formatPrice(product.price)} {product.mrp&&<span className="ml-2 text-sm font-normal text-muted-foreground line-through">{formatPrice(product.mrp)}</span>} {product.mrp&&<span className="ml-2 text-sm text-offer">17% off</span>}</p><p className="mt-1 text-[10px] text-muted-foreground">Inclusive of applicable taxes</p>
      <div className="mt-8"><div className="flex justify-between text-xs"><b>Colour: <span className="font-normal capitalize">{colour}</span></b><span>{product.colors.length} colours</span></div><div className="mt-3 flex gap-3">{product.colors.map((color,index)=><button key={color} onClick={()=>setColour(color)} aria-label={color} className={`h-9 w-9 rounded-full border-2 p-1 ${colour===color?"border-foreground":"border-transparent"}`}><span className={`block h-full w-full rounded-full swatch-${index%5}`}/></button>)}</div></div>
      <div id="sizes" className="mt-8"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-widest">Select size</p><button onClick={()=>setGuide(true)} className="flex items-center gap-1 text-xs underline"><Ruler size={14}/> Size guide</button></div><div className="mt-3 grid grid-cols-5 gap-2">{sizes.map((item,index)=><button key={item} disabled={index===4} onClick={()=>setSize(item)} className={`h-11 border text-xs ${size===item?"border-primary bg-primary text-primary-foreground":"border-border"} disabled:cursor-not-allowed disabled:bg-muted disabled:text-muted-foreground disabled:line-through`}>{item}</button>)}</div><div className="mt-3 flex items-center justify-between text-xs"><span>Model is 5'8″ and wears size S</span><button className="font-semibold underline">My Size <span className="font-normal text-muted-foreground">(coming soon)</span></button></div>{!size&&<p className="mt-3 text-xs text-muted-foreground">Choose a size before adding to bag.</p>}</div>
      <Button className="mt-7 hidden w-full md:flex" onClick={add}>Add to bag · {formatPrice(product.price)}</Button>
      <div className="mt-8 border-y border-border py-5"><p className="text-xs font-bold uppercase tracking-widest">Delivery</p><div className="mt-3 flex border border-input"><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="Enter 6-digit pincode" className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none"/><Button variant="ghost" size="sm" onClick={checkPin}>Check</Button></div>{delivery==="checking"&&<p className="mt-3 text-xs text-muted-foreground">Checking delivery options…</p>}{delivery==="yes"&&<p className="mt-3 flex gap-2 text-xs"><Check size={14} className="text-success"/> Delivery available. Estimated 3–5 business days. COD shown at checkout if available.</p>}{delivery==="no"&&<p className="mt-3 text-xs text-destructive">Enter a valid 6-digit pincode to check delivery.</p>}</div>
      <div className="divide-y divide-border">{[["Product details","Structured midi silhouette with panelled bodice, square neckline and softly pleated skirt."],["Fit & size","Close fit through the bodice, relaxed through the skirt. If between sizes, choose the larger size."],["Fabric & care","Cotton-satin blend. Gentle cold wash separately. Dry in shade. Cool iron."],["Style notes","Pair with minimal heels for evenings, or layer with a cropped jacket for daytime."],["Shipping, returns & exchange","Delivery estimates depend on your pincode. Final eligibility and timelines are shown at checkout."],["Manufacturing information","Sample prototype content. Country of origin: India. Manufacturer details will be supplied by the production catalogue."]].map(([title,text])=><details key={title} className="py-5"><summary className="flex cursor-pointer list-none justify-between text-sm font-medium">{title}<Plus size={16}/></summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></details>)}</div>
    </div></aside>
  </section>
  <Reviews/>
  <CompleteLook/>
  <Bundle/>
  <section className="mx-auto max-w-[1440px] px-4 py-16 md:px-8"><SectionTitle eyebrow="Keep exploring" title="You may also like"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{products.slice(2,6).map(p=><ProductCard product={p} key={p.slug}/>)}</div></section>
  <section className="mx-auto max-w-[1440px] border-t border-border px-4 py-16 md:px-8"><SectionTitle title="Recently viewed"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><ProductCard product={product}/></div></section>
  <div className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-[auto_1fr] gap-2 border-t border-border bg-background p-3 md:hidden"><Button variant="outline" size="icon" onClick={()=>toggleWish(product.slug)}><Heart size={18}/></Button><Button onClick={add}>{size?`Add size ${size} · ${formatPrice(product.price)}`:"Select size to add"}</Button></div>
  {guide&&<div className="fixed inset-0 z-50 flex items-end bg-overlay md:items-center md:justify-center" onClick={()=>setGuide(false)}><div className="w-full bg-background p-6 md:max-w-lg" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="font-display text-3xl">Size guide</h2><Button variant="ghost" size="icon" onClick={()=>setGuide(false)}><Minus/></Button></div><table className="mt-6 w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="py-3">Size</th><th>Bust</th><th>Waist</th><th>Hip</th></tr></thead><tbody>{[["XS","32","25","35"],["S","34","27","37"],["M","36","29","39"],["L","38","31","41"],["XL","40","33","43"]].map(row=><tr className="border-b border-border" key={row[0]}>{row.map(cell=><td className="py-3" key={cell}>{cell}</td>)}</tr>)}</tbody></table><p className="mt-4 text-xs text-muted-foreground">Body measurements in inches. My Size recommendations will be available in a future release.</p></div></div>}
  </main> }
function Reviews(){return <section className="mt-16 bg-secondary py-16"><div className="mx-auto max-w-[1200px] px-4 md:px-8"><SectionTitle eyebrow="Sample content" title="Ratings & reviews"/><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><p className="font-display text-6xl">4.6</p><p className="mt-2 flex text-accent">★★★★★</p><p className="mt-2 text-xs text-muted-foreground">Based on 38 sample reviews</p>{[5,4,3,2,1].map((n,i)=><div className="mt-3 flex items-center gap-3 text-xs" key={n}><span>{n}</span><div className="h-1.5 flex-1 bg-border"><div className="h-full bg-accent" style={{width:`${[76,18,5,1,0][i]}%`}}/></div></div>)}<Button variant="outline" className="mt-7">Write a review</Button></div><div className="space-y-5">{[["Beautiful shape","The bodice feels structured and the skirt moves beautifully.","Sample reviewer · Verified purchase"],["Colour is rich","Exactly the statement red I was hoping for. Check the guide for a close fit.","Sample reviewer · Verified purchase"]].map(([title,text,by])=><article className="border-b border-border pb-5" key={title}><p className="text-accent">★★★★★</p><h3 className="mt-2 font-medium">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p><p className="mt-3 text-[10px] uppercase tracking-widest">{by}</p></article>)}</div></div></div></section>}
function CompleteLook(){return <section className="mx-auto max-w-[1440px] px-4 py-16 md:px-8 md:py-24"><SectionTitle eyebrow="Styled for you" title="Complete the look"/><div className="grid gap-8 md:grid-cols-[1.25fr_.75fr]"><img src={campaignHero} alt="Complete the look styling" loading="lazy" width={1536} height={1024} className="h-full min-h-[420px] w-full object-cover"/><div className="space-y-3">{products.slice(1,4).map((p,index)=><label className="grid grid-cols-[auto_72px_1fr_auto] items-center gap-3 border-b border-border py-3" key={p.slug}><input type="checkbox" defaultChecked={index<2}/><img src={p.image} alt="" className="h-20 w-16 object-cover" style={p.position?{objectPosition:p.position}:undefined}/><span className="text-sm">{p.name}<small className="mt-1 block text-muted-foreground">{formatPrice(p.price)} · Choose size on product page</small></span><Link to="/product/$slug" params={{slug:p.slug}}><ChevronDown className="-rotate-90" size={16}/></Link></label>)}<Button className="mt-4 w-full">Add 2 selected items</Button></div></div></section>}
function Bundle(){const {addToBag}=useShop();return <section className="bg-muted py-16"><div className="mx-auto max-w-[1100px] px-4 md:px-8"><SectionTitle eyebrow="Pairs well" title="Frequently bought together"/><div className="grid gap-7 md:grid-cols-[1fr_auto] md:items-end"><div className="grid grid-cols-3 gap-3">{products.slice(0,3).map((p,index)=><label key={p.slug} className="text-xs"><div className="relative aspect-[3/4] overflow-hidden"><img src={p.image} alt={p.name} className="h-full w-full object-cover" style={p.position?{objectPosition:p.position}:undefined}/><input type="checkbox" defaultChecked className="absolute left-2 top-2 h-4 w-4 accent-primary"/></div><p className="mt-2 truncate">{index===0?"This item":p.name}</p><p>{formatPrice(p.price)}</p></label>)}</div><div><p className="text-xs text-muted-foreground">3 items selected</p><p className="mt-1 text-xl font-semibold">{formatPrice(products.slice(0,3).reduce((sum,p)=>sum+p.price,0))}</p><Button className="mt-4 w-full" onClick={()=>addToBag(3)}>Add selected to bag</Button></div></div></div></section>}
