import { createFileRoute } from "@tanstack/react-router";
import { ChevronDown, SlidersHorizontal, X } from "lucide-react";
import { useState } from "react";
import { z } from "zod";
import { Button, ProductCard } from "@/components/ui";
import { products } from "@/lib/catalog";

const shopSearchSchema = z.object({ for: z.string().optional() });
export const Route = createFileRoute("/shop")({
  validateSearch: (search) => shopSearchSchema.parse(search),
  head: () => ({ meta: [
    { title: "Shop New Fashion — AARO" }, { name: "description", content: "Browse the latest AARO apparel with filters for size, colour, fit, fabric, occasion, and collection." },
    { property: "og:title", content: "Shop New Fashion — AARO" }, { property: "og:description", content: "A considered edit of modern womenswear and menswear." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: ShopPage,
});
const filters = ["Category","Size","Colour","Price","Fit","Fabric","Occasion","Collection","Discount","Availability"];
function FilterPanel({close}:{close?:()=>void}) { return <div className="bg-background"><div className="flex items-center justify-between pb-5"><p className="text-xs font-bold uppercase tracking-widest">Filters</p>{close&&<Button variant="ghost" size="icon" onClick={close}><X size={18}/></Button>}</div>{filters.map((filter,index)=><details key={filter} className="border-t border-border py-4" open={index<2}><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-medium">{filter}<ChevronDown size={16}/></summary><div className="mt-4 grid gap-3 text-sm text-muted-foreground">{(filter==="Size"?["XS","S","M","L","XL"]:["Everyday","Work","Occasion"]).map(option=><label className="flex items-center gap-3" key={option}><input type="checkbox" className="h-4 w-4 accent-primary"/> {option}</label>)}</div></details>)}</div> }
function ShopPage(){const { for: audience }=Route.useSearch(); const [filtersOpen,setFiltersOpen]=useState(false); return <main><section className="border-b border-border bg-secondary px-4 py-12 text-center md:py-16"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-accent">The current edit</p><h1 className="mt-3 font-display text-5xl capitalize md:text-7xl">{audience && audience!=="all"?audience:"Shop all"}</h1><p className="mx-auto mt-3 max-w-md text-sm text-muted-foreground">Relaxed tailoring, expressive colour, and easy everyday layers.</p></section><section className="mx-auto max-w-[1440px] px-4 py-8 md:px-8"><div className="mb-7 grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-2 border-b border-border pb-4"><p className="min-w-0 text-xs text-muted-foreground">{products.length} styles</p><Button variant="outline" size="sm" className="md:hidden" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={14} className="mr-2"/> Filter</Button><Button variant="ghost" size="sm">Sort: Featured <ChevronDown size={14} className="ml-2"/></Button></div><div className="grid gap-8 md:grid-cols-[220px_1fr]"><aside className="hidden md:block"><FilterPanel/></aside><div className="grid grid-cols-2 gap-x-3 gap-y-9 lg:grid-cols-3 xl:grid-cols-4 md:gap-x-5">{products.map(product=><ProductCard key={product.slug} product={product}/>)}</div></div></section>{filtersOpen&&<div className="fixed inset-0 z-50 flex items-end bg-overlay md:hidden" onClick={()=>setFiltersOpen(false)}><div className="max-h-[85svh] w-full overflow-y-auto bg-background p-5" onClick={event=>event.stopPropagation()}><FilterPanel close={()=>setFiltersOpen(false)}/><div className="sticky bottom-0 bg-background pt-4"><Button className="w-full" onClick={()=>setFiltersOpen(false)}>Show {products.length} styles</Button></div></div></div>}</main>}
